### ISSUE TITLE
Change `okhttp-logging-interceptor` to `okhttp-interceptor-logging` + Same for Retrofit

### ISSUE THREAD

**Issue by danielPerez97** [danielPerez97/Scaler#1]
OkHttp can use multiple interceptor libraries. This change will keep things consistent in the libs.versions.toml
```toml
# Before
okhttp-1-interceptor = ...
okhttp-2-inteceptor = ...

# After
okhttp-interceptor-1=...
okhttp-interceptor-2=...
okhttp-interceptor-3=...
```

This simplifies the call sites:
```kotlin
dependencies {
    // Before
    libs.1.interceptor
    libs.2.interceptor

    // After
    libs.interceptor.1
    libs.interceptor.2
}
```

Same thing for Retrofit adapters + converters
